env:
  browser: true
  es6: true
  node: true
extends: airbnb
globals:
  Atomics: readable
  SharedArrayBuffer: readable
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  import/no-unresolved: 0
  no-console: 0
